sudo: false
language: php
php:
- 7
install:
- nvm install 6
- npm install
script:
- ".travis-build/phplint ."
after_success:
- npm run prod
- rm -rf node_modules
- tar -czf counseling.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: JROiJALvmW13HaUqdzbKuDsn5oXASh3UO1H9jkz3M9ZmwUb1vzSAR8LUPlxjDOa+zn5YKHUcmWEs66oyGWS9iyhOkUfQDnqy6+54klUk86RhygSEGJo4m0wUjjmTXEIMmn9oqh7HI1hQvSVhBtiJIiNsvZiB3f/h5SmU72jwu1w=
  file: counseling.tar.gz
  on:
    repo: AppStateESS/counseling
